In [ ]:
import numpy as np

In [ ]:
# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("1. Empty array:\n", empty_array)

# 2. Initialize an all one array with size 4x2
ones_array = np.ones((4, 2))
print("\n2. All ones array:\n", ones_array)

# 3. Return a new array filled with fill_value
full_array = np.full((3, 3), 5)  # 3x3 array filled with 5
print("\n3. Full array:\n", full_array)

# 4. Return a new array of zeros with same shape and type as given array
sample_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(sample_array)
print("\n4. Zeros like array:\n", zeros_like_array)

# 5. Return a new array of ones with same shape and type as given array
ones_like_array = np.ones_like(sample_array)
print("\n5. Ones like array:\n", ones_like_array)

# 6. Convert list to numpy array
new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("\n6. Array from list:", array_from_list)


1. Empty array:
 [[3.85888818e-315 0.00000000e+000]
 [6.86929164e-310 6.86929164e-310]]

2. All ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Full array:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]

4. Zeros like array:
 [[0 0]
 [0 0]]

5. Ones like array:
 [[1 1]
 [1 1]]

6. Array from list: [1 2 3 4]


In [ ]:
import numpy as np

# 1. Create array with values from 10 to 49
arr1 = np.arange(10, 50)
print("1. Array from 10 to 49:", arr1)

# 2. Create 3x3 matrix with values from 0 to 8
arr2 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix:\n", arr2)

# 3. Create 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3. Identity matrix:\n", identity_matrix)

# 4. Create random array of size 30 and find mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print(f"\n4. Random array mean: {mean_value}")

# 5. Create 10x10 random array and find min/max
large_random = np.random.random((10, 10))
min_val, max_val = large_random.min(), large_random.max()
print(f"\n5. Min: {min_val}, Max: {max_val}")

# 6. Create zero array and replace 5th element with 1
zero_arr = np.zeros(10)
zero_arr[4] = 1  # 5th element (0-indexed)
print("\n6. Zero array with 5th element as 1:", zero_arr)

# 7. Reverse an array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reversed array:", reversed_arr)

# 8. Create 2D array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n8. Border array:\n", border_array)

# 9. Create 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. Checkerboard pattern:\n", checkerboard)


1. Array from 10 to 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array mean: 0.4477960684364905

5. Min: 0.0026474214834961707, Max: 0.9990853407736648

6. Zero array with 5th element as 1: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed array: [0 4 0 0 2 1]

8. Border array:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. Checkerboard pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_result = x + y
print("1. Addition:\n", add_result)

# 2. Subtract the two arrays
sub_result = x - y
print("\n2. Subtraction:\n", sub_result)

# 3. Multiply array with integer
mult_result = x * 3
print("\n3. Multiplication by 3:\n", mult_result)

# 4. Square of each element
square_result = x ** 2
print("\n4. Square of elements:\n", square_result)

# 5. Dot products
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print(f"\n5. Dot products:")
print(f"v·w: {dot_vw}")
print(f"x·v: {dot_xv}")
print(f"x·y:\n{dot_xy}")

# 6. Concatenation
concat_row = np.concatenate((x, y), axis=0)
concat_col = np.concatenate((v, w), axis=0)  # For 1D arrays
print(f"\n6. Concatenation:")
print(f"x and y along row:\n{concat_row}")
print(f"v and w along column: {concat_col}")

# 7. Concatenate x and v (this will cause error)
try:
    error_result = np.concatenate((x, v))
    print("\n7. Concatenation result:", error_result)
except ValueError as e:
    print(f"\n7. Error when concatenating x and v: {e}")
    print("Explanation: Arrays must have the same number of dimensions for concatenation.")


1. Addition:
 [[ 6  8]
 [10 13]]

2. Subtraction:
 [[-4 -4]
 [-4 -3]]

3. Multiplication by 3:
 [[ 3  6]
 [ 9 15]]

4. Square of elements:
 [[ 1  4]
 [ 9 25]]

5. Dot products:
v·w: 219
x·v: [29 77]
x·y:
[[19 22]
 [50 58]]

6. Concatenation:
x and y along row:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
v and w along column: [ 9 10 11 12]

7. Error when concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: Arrays must have the same number of dimensions for concatenation.


In [ ]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A·A⁻¹ = I
A_inv = np.linalg.inv(A)
identity_check = np.dot(A, A_inv)
print("1. A·A⁻¹ (should be identity matrix):\n", identity_check)
print("Is it identity matrix?", np.allclose(identity_check, np.eye(2)))

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print(f"\n2. AB:\n{AB}")
print(f"BA:\n{BA}")
print("Are they equal?", np.array_equal(AB, BA))

# 3. Prove (AB)ᵀ = BᵀAᵀ
AB_transpose = AB.T
B_transpose_A_transpose = np.dot(B.T, A.T)
print(f"\n3. (AB)ᵀ:\n{AB_transpose}")
print(f"BᵀAᵀ:\n{B_transpose_A_transpose}")
print("Are they equal?", np.array_equal(AB_transpose, B_transpose_A_transpose))

# Solve system of linear equations
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Matrix form: AX = B
A_matrix = np.array([[2, -3, 1],
                     [1, -1, 2],
                     [3, 1, -1]])
B_vector = np.array([-1, -3, 9])

# Using inverse method
A_inv = np.linalg.inv(A_matrix)
X_solution = np.dot(A_inv, B_vector)
print(f"\nSolution using inverse method: {X_solution}")

# Using linalg.solve (more efficient)
X_solution_solve = np.linalg.solve(A_matrix, B_vector)
print(f"Solution using np.linalg.solve: {X_solution_solve}")

# Verify solution
verification = np.dot(A_matrix, X_solution_solve)
print(f"Verification (should equal B): {verification}")


1. A·A⁻¹ (should be identity matrix):
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is it identity matrix? True

2. AB:
[[23 13]
 [51 29]]
BA:
[[36 44]
 [13 16]]
Are they equal? False

3. (AB)ᵀ:
[[23 51]
 [13 29]]
BᵀAᵀ:
[[23 51]
 [13 29]]
Are they equal? True

Solution using inverse method: [ 2.  1. -2.]
Solution using np.linalg.solve: [ 2.  1. -2.]
Verification (should equal B): [-1. -3.  9.]


In [ ]:
import numpy as np
import time

# 1. Element-wise Addition
print("1. ELEMENT-WISE ADDITION")

# Python Lists
size = 1000000
list1 = list(range(size))
list2 = list(range(size, 2*size))

start_time = time.time()
result_list = [a + b for a, b in zip(list1, list2)]
list_time = time.time() - start_time
print(f"Python lists time: {list_time:.6f} seconds")

# NumPy Arrays
arr1 = np.arange(size)
arr2 = np.arange(size, 2*size)

start_time = time.time()
result_arr = arr1 + arr2
numpy_time = time.time() - start_time
print(f"NumPy arrays time: {numpy_time:.6f} seconds")
print(f"NumPy is {list_time/numpy_time:.2f}x faster")

# 2. Element-wise Multiplication
print("\n2. ELEMENT-WISE MULTIPLICATION")

# Python Lists
start_time = time.time()
result_list = [a * b for a, b in zip(list1, list2)]
list_time = time.time() - start_time
print(f"Python lists time: {list_time:.6f} seconds")

# NumPy Arrays
start_time = time.time()
result_arr = arr1 * arr2
numpy_time = time.time() - start_time
print(f"NumPy arrays time: {numpy_time:.6f} seconds")
print(f"NumPy is {list_time/numpy_time:.2f}x faster")

# 3. Dot Product
print("\n3. DOT PRODUCT")

# Python Lists
start_time = time.time()
dot_list = sum(a * b for a, b in zip(list1, list2))
list_time = time.time() - start_time
print(f"Python lists time: {list_time:.6f} seconds")

# NumPy Arrays
start_time = time.time()
dot_numpy = np.dot(arr1, arr2)
numpy_time = time.time() - start_time
print(f"NumPy arrays time: {numpy_time:.6f} seconds")
print(f"NumPy is {list_time/numpy_time:.2f}x faster")

# 4. Matrix Multiplication
print("\n4. MATRIX MULTIPLICATION")

size_mat = 100

# Python Lists (using smaller size for demonstration)
matrix1 = [[i + j for j in range(size_mat)] for i in range(size_mat)]
matrix2 = [[i - j for j in range(size_mat)] for i in range(size_mat)]

start_time = time.time()
result_matrix = [[0 for _ in range(size_mat)] for _ in range(size_mat)]
for i in range(size_mat):
    for j in range(size_mat):
        for k in range(size_mat):
            result_matrix[i][j] += matrix1[i][k] * matrix2[k][j]
list_time = time.time() - start_time
print(f"Python lists time: {list_time:.6f} seconds")

# NumPy Arrays
np_matrix1 = np.array(matrix1)
np_matrix2 = np.array(matrix2)

start_time = time.time()
result_np = np.dot(np_matrix1, np_matrix2)
numpy_time = time.time() - start_time
print(f"NumPy arrays time: {numpy_time:.6f} seconds")
print(f"NumPy is {list_time/numpy_time:.2f}x faster")

1. ELEMENT-WISE ADDITION
Python lists time: 0.071940 seconds
NumPy arrays time: 0.004374 seconds
NumPy is 16.45x faster

2. ELEMENT-WISE MULTIPLICATION
Python lists time: 0.210694 seconds
NumPy arrays time: 0.011275 seconds
NumPy is 18.69x faster

3. DOT PRODUCT
Python lists time: 0.194239 seconds
NumPy arrays time: 0.002151 seconds
NumPy is 90.29x faster

4. MATRIX MULTIPLICATION
Python lists time: 0.818915 seconds
NumPy arrays time: 0.006060 seconds
NumPy is 135.14x faster
